run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosec
    - stylecheck
    - typecheck
    - gocritic
    - gofmt
    - goimports
  exclude-use-default: false

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G404:" # Ignore weak random number generator lint. We do not need strong randomness here.
    - linters:
        - stylecheck
      text: "ST1018:" # Ignore Unicode format character warnings

  exclude:
    - "should have comment or be unexported"
